import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { SignInBtn } from "../../components/SignInBtn";
import { SignOutBtn } from "../../components/SignOutBtn";
import { auth } from "./auth";
import {SessionProvider} from "@/context/SessionContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full px-8 py-3 flex items-center shadow-2xl">
          <nav className="flex justify-between items-center w-full">
            <Link href={"/"} className="h-full">
              Homepage
            </Link>
            <ul className="flex items-center gap-8">
              <li>
                <Link href={"/favorites"} className="hover:bg-white">
                  Favorites
                </Link>
              </li>
              <li>
                <Link href={"/people"} className="hover:bg-white">
                  Actors
                </Link>
              </li>
              {session === null ? (
                <li>
                  <SignInBtn></SignInBtn>
                </li>
              ) : (
                <li>
                  <SignOutBtn></SignOutBtn>
                </li>
              )}
            </ul>
          </nav>
        </header>
        <SessionProvider value={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
