import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full px-8 py-3 flex items-center shadow-2xl">
          <nav className="flex justify-between items-center w-full">
            <Link href={"/"} className="h-full">
              Homepage
            </Link>
            <ul className="flex items-center gap-8">
              <li>
                <Link
                  href={"/favorites/favoriteShows"}
                  className="hover:bg-white"
                >
                  Favorites
                </Link>
              </li>
              <li>
                <Link href={"/actors"} className="hover:bg-white">
                  Actors
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
